<?xml version="1.0" encoding="UTF-8"?><testrun name="testTinvariante" project="Fabrica Concurrente" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="Testing.testTinvariante" time="10.052">
    <testcase name="testInvariante" classname="Testing.testTinvariante" time="10.052">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds&#13;
	at java.lang.Object.wait(Native Method)&#13;
	at java.lang.Thread.join(Unknown Source)&#13;
	at java.lang.Thread.join(Unknown Source)&#13;
	at Testing.testTinvariante.testInvariante(testTinvariante.java:82)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)&#13;
	at java.util.concurrent.FutureTask.run(Unknown Source)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
